# Generated by Django 3.1.5 on 2021-03-08 02:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre de Categoría', max_length=50, unique=True)),
                ('descripcion', models.TextField(blank=True, max_length=70, null=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='Categorias')),
            ],
            options={
                'verbose_name_plural': 'Categorías',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Emprendedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=10, unique=True, verbose_name='cédula')),
                ('nombres', models.CharField(max_length=20)),
                ('apellidos', models.CharField(max_length=20)),
                ('direccion', models.CharField(max_length=150, verbose_name='dirección')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='Emprendedores')),
                ('tfno', models.CharField(max_length=10, verbose_name='teléfono')),
            ],
            options={
                'verbose_name_plural': 'Emprendedores',
                'ordering': ['nombres', 'apellidos'],
            },
        ),
        migrations.CreateModel(
            name='Emprendimiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción del Emprendimiento', max_length=100, null=True, verbose_name='descripción')),
                ('direccion', models.CharField(help_text='Dirección del emprendimiento', max_length=150, verbose_name='dirección')),
                ('fecha_creación', models.DateField(verbose_name='fecha de creación')),
                ('imagen', models.ImageField(upload_to='Emprendimientos')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bases.categoria')),
                ('emprendedores', models.ManyToManyField(to='bases.Emprendedor')),
            ],
            options={
                'verbose_name_plural': 'Emprendimientos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='código')),
                ('nombre', models.CharField(max_length=30)),
                ('marca', models.CharField(max_length=20)),
                ('descripcion', models.CharField(blank=True, help_text='Descripción del Producto', max_length=100, null=True, verbose_name='descripción')),
                ('precio', models.FloatField(default=0)),
                ('imagen', models.ImageField(upload_to='Productos')),
                ('emprendimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bases.emprendimiento')),
            ],
            options={
                'verbose_name_plural': 'Productos',
                'ordering': ['nombre'],
            },
        ),
    ]
