# Generated by Django 3.1.5 on 2021-03-21 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bases', '0002_auto_20210320_2142'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emprendedor',
            old_name='instragram',
            new_name='instagram',
        ),
    ]
