# Generated by Django 3.1.5 on 2021-03-29 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bases', '0005_contacto_asunto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contacto',
            old_name='Asunto',
            new_name='asunto',
        ),
    ]
