# Generated by Django 3.1.5 on 2021-03-29 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bases', '0006_auto_20210329_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='asunto',
            field=models.CharField(max_length=120),
        ),
    ]
